# Site settings
title: Sagaciasoft
email: contact@sagaciasoft.com
baseurl:
url: https://sagaciasoft.com
description: "The ones who are crazy enough to think they can change the world, are the ones that do."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#9f11d4'

# Footer settings
footer: Sagaciasoft

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/profile.php?id=61556977785506
  - title: linkedin
    url: https://www.linkedin.com/company/sagaciasoft
  - title: instagram
    url: https://www.instagram.com/sagaciasoft/

# Build settings
markdown: kramdown
permalink: pretty
