# Site settings
title: Sagaciasoft
email: contact@sagaciasoft.com
baseurl:
url: https://sagaciasoft.com
description: A sagacious individual once said, "Writing software takes sagacity, possibly even sagacia."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#9f11d4'

# Footer settings
footer: Sagaciasoft

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/yoans
  - title: facebook
    url: https://www.facebook.com/youngmanathan
  - title: linkedin
    url: https://www.linkedin.com/in/nathaniel-young-b1033a18/
  - title: instagram
    url: https://www.instagram.com/nathanyoans/
  - title: steam
    url: https://steamcommunity.com/id/yoans
  - title: soundcloud
    url: https://soundcloud.com/nathaniel-pierce-young

# Build settings
markdown: kramdown
permalink: pretty
